### ISSUE TITLE
Arquiterura

### ISSUE THREAD

**Issue by DevJoseWeb** [acenelio/springboot2-ionic-backend#2]
Professor ja que não tenho outro meio de comunicação com o senhor tive que usar este !
A minha pergunta pode ser a de muitos, quando este padrão deixa de atender e tenho que usar mensageria....

O senhor indica algum livro tutorial sobre o assunto !

Att..

**Comment by acenelio** [comment]
Caro Jose. Não conheço um livro atualizado que trate de forma prática e objetiva o assunto. Você é meu aluno na Udemy?

**Comment by DevJoseWeb** [comment]
Sim eu sou, fiz o curso completo ! de Java e quando der tempo vou fazer o C· e estou aguardando sair o de Grap
